### ISSUE TITLE
Running upgradeProxy script results in CONTRACT_REVERT_EXECUTED

### ISSUE THREAD

**Issue by JordyKingz** [hashgraph/hedera-smart-contract-starter#10]
The upgradeProxy script doesn't seems to work as expected. Upgrading the Bank.sol contract results in CONTRACT_REVERT_EXECUTED

`npx hardhat run deployment/scripts/deploy.ts`

```
Deploying (Bank) contract, where file path is (artifacts/contracts/Bank.sol/Bank.json)

STEP 1 - Create file
- The smart contract bytecode file ID is: 0.0.4378079
- Content added

STEP 2 - Create contract
- Contract created 0.0.4378081, Contract Address 000000000000000000000000000000000042cde1
Contract id 0.0.4378081
Contract details [
    {
        "name": "Bank",
        "id": "0.0.4378081",
        "address": "0x000000000000000000000000000000000042cde1",
        "timestamp": "2023-04-24T12:12:30.303Z",
        "hash": ""
    }
]
Bank deployed successfully => {"id":"0.0.4378081","address":"0x000000000000000000000000000000000042cde1"}
contractName: Bank
contractName: 0.0.4378081

STEP 1 - Create file
- The smart contract bytecode file ID is: 0.0.4378082
- Content added

STEP 2 - Create contract
- Contract created 0.0.4378086, Contract Address 000000000000000000000000000000000042cde6
Contract id 0.0.4378086
Contract details [
    {
        "name": "Bank",
        "id": "0.0.4378081",
        "address": "0x000000000000000000000000000000000042cde1",
        "timestamp": "2023-04-24T12:12:30.303Z",
        "hash": ""
    },
    {
        "name": "TransparentUpgradeableProxy",
        "id": "0.0.4378086",
        "address": "0x000000000000000000000000000000000042cde6",
        "timestamp": "2023-04-24T12:12:36.758Z",
        "hash": ""
    }
]
TransparentUpgradeableProxy deployed - 0.0.4378086
Contract record updated [
    {
        "name": "TransparentUpgradeableProxy",
        "id": "0.0.4378086",
        "address": "0x000000000000000000000000000000000042cde6",
        "timestamp": "2023-04-24T12:12:36.758Z",
        "hash": ""
    },
    {
        "name": "Bank",
        "id": "0.0.4378081",
        "address": "0x000000000000000000000000000000000042cde1",
        "timestamp": "2023-04-24T12:12:36.760Z",
        "hash": "",
        "transparentProxyAddress": "0x000000000000000000000000000000000042cde6",
        "transparentProxyId": "0.0.4378086"
    }
]
Done
```

`npx hardhat run deployment/scripts/upgradeProxy.ts`

```
ReceiptStatusError: receipt for transaction 0.0.3804814@1682338407.845284254 contained error status CONTRACT_REVERT_EXECUTED
    at new ReceiptStatusError (/Users/user/hedera-smart-contract-starter/node_modules/@hashgraph/sdk/lib/ReceiptStatusError.cjs:43:5)
    at TransactionReceiptQuery._mapStatusError (/Users/user/hedera-smart-contract-starter/node_modules/@hashgraph/sdk/lib/transaction/TransactionReceiptQuery.cjs:273:12)
    at TransactionReceiptQuery.execute (/Users/user/hedera-smart-contract-starter/node_modules/@hashgraph/sdk/lib/Executable.cjs:644:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TransactionResponse.getReceipt (/Users/user/hedera-smart-contract-starter/node_modules/@hashgraph/sdk/lib/transaction/TransactionResponse.cjs:88:21)
    at async TransactionResponse.getRecord (/Users/user/hedera-smart-contract-starter/node_modules/@hashgraph/sdk/lib/transaction/TransactionResponse.cjs:104:5)
    at async getAdmin (/Users/user/hedera-smart-contract-starter/deployment/scripts/upgradeProxy.ts:44:20)
    at async main (/Users/user/hedera-smart-contract-starter/deployment/scripts/upgradeProxy.ts:80:3) {
  status: Status { _code: 33 },
  transactionId: TransactionId {
    accountId: AccountId {
      shard: [Long],
      realm: [Long],
      num: [Long],
      aliasKey: null,
      evmAddress: null,
      _checksum: null
    },
    validStart: Timestamp { seconds: [Long], nanos: [Long] },
    scheduled: false,
    nonce: null
  },
  transactionReceipt: TransactionReceipt {
    status: Status { _code: 33 },
    accountId: null,
    fileId: null,
    contractId: ContractId {
      shard: [Long],
      realm: [Long],
      num: [Long],
      evmAddress: null,
      _checksum: null
    },
    topicId: null,
    tokenId: null,
    scheduleId: null,
    exchangeRate: ExchangeRate {
      hbars: 30000,
      cents: 180115,
      expirationTime: 2023-04-24T13:00:00.000Z,
      exchangeRateInCents: 6.003833333333334
    },
    topicSequenceNumber: Long { low: 0, high: 0, unsigned: false },
    topicRunningHash: Uint8Array(0) [],
    totalSupply: Long { low: 0, high: 0, unsigned: false },
    scheduledTransactionId: null,
    serials: [],
    duplicates: [],
    children: []
  }
}
```

**Comment by mgarbs** [comment]
Hi @JordyKingz our network had a security update and as part of the update as it relates to this repo, Ive done away with hethers and implemented proxy and beacon proxy upgrades using ethers which is what most devs are used to. Here is the PR if you're interested: https://github.com/hashgraph/hedera-smart-contract-starter/pull/11
